fixtures:
    forge_modules:
        concat:
            repo: "puppetlabs/concat"
            ref: "1.2.5"
    repositories:
        "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    symlinks:
        "bind": "#{source_dir}"
