HOSTS:
  ubuntu-12-04:
    roles:
     - master
     - database
     - dashboard
    platform: ubuntu-12.04-x64
    image: ubuntu:12.04
    hypervisor: docker
    docker_image_commands: 
      - 'apt-get update -o Acquire::http::No-Cache=true -o Acquire::http::Pipeline-Depth=0' 
    
CONFIG:
  type: foss
