HOSTS:
    ubuntu-server-1404-x64-master:
        roles:
         - master
        platform: ubuntu-14.04-x64
        image: solarkennedy/ubuntu-14.04-puppet
        hypervisor: docker
        docker_preserve_image: false
        docker_image_commands: 
         - "sed --in-place=.bak 's/without-password/yes/' /etc/ssh/sshd_config"
    ubuntu-server-1404-x64-slave:
        roles:
         - database
        platform: ubuntu-14.04-x64
        image: solarkennedy/ubuntu-14.04-puppet
        hypervisor: docker
        docker_preserve_image: false
        docker_image_commands: 
         - "sed --in-place=.bak 's/without-password/yes/' /etc/ssh/sshd_config"
CONFIG:
    type: foss

