HOSTS:
    ubuntu-server-1404-x64-master:
        roles:
         - master
        platform: ubuntu-14.04-x64
        image: ubuntu:14.04
        hypervisor: docker
        docker_preserve_image: true
        docker_image_commands: 
         - wget --no-check-certificate https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
         - apt-get install -y wget ca-certificates
         - dpkg -i puppetlabs-release-trusty.deb
         - apt-get update
         - apt-get -y install puppet curl ntpdate git ruby
         - "sed --in-place=.bak 's/without-password/yes/' /etc/ssh/sshd_config"
    ubuntu-server-1404-x64-slave:
        roles:
         - database
        platform: ubuntu-14.04-x64
        image: ubuntu:14.04
        hypervisor: docker
        docker_preserve_image: true
        docker_image_commands: 
         - wget --no-check-certificate https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
         - apt-get install -y wget ca-certificates
         - dpkg -i puppetlabs-release-trusty.deb
         - apt-get update
         - apt-get -y install puppet curl ntpdate git ruby
         - "sed --in-place=.bak 's/without-password/yes/' /etc/ssh/sshd_config"
CONFIG:
    type: foss

